home/api/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.get_routes),
    path('rooms/', views.get_rooms),
    path('room/<str:pk>/', views.get_room),

    path('topics/', views.get_topics)


]

home/urls.py
from django.urls import path
from . import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', views.index, name='index'),
    path('room/<str:pk>/', views.room, name='room'),
    path('topics/', views.topics, name='topics'),
    path('activity/', views.activity, name='activity'),

    ## User Section
    path('settings/', views.profile_settings, name='profile_settings'),
    path('profile/<str:pk>/', views.user_profile, name='profile'),

    ## Room CRUD
    path('create-room/',views.create_room, name='create_room'),
    path('update-room/<str:pk>/',views.update_room, name='update_room'),
    path('delete-room/<str:pk>/',views.delete_room, name='delete_room'),
    path('delete-message/<str:pk>/',views.delete_message, name='delete_message'),

    ## Authentication
    path('login/', views.login_user, name='login_user'),
    path('logout/', views.logout_user, name='logout_user'),
    path('register/', views.register_user, name='register_user'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class User(AbstractUser):
    name = models.CharField(max_length=200, null=True)
    email = models.EmailField(unique=True, null=True)
    bio = models.TextField(null=True)
    avatar = models.ImageField(null=True, default="avatar.svg")

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username']

    def __str__(self):
        return self.username


class Topic(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name

class Room(models.Model):
    name = models.CharField(max_length=255, unique=True, null=False)
    host = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    topic = models.ForeignKey(Topic, on_delete=models.SET_NULL, null=True)
    description = models.TextField(null=True, blank=True)
    participants = models.ManyToManyField(User, related_name='participants', blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-updated_at','-created_at']

    def __str__(self):
        return self.name

class Message(models.Model):
    host = models.ForeignKey(User, on_delete=models.CASCADE)
    room = models.ForeignKey(Room, on_delete=models.CASCADE)
    body = models.TextField(null=False)
    updated_at = models.DateTimeField(auto_now=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.body[:50]

home/forms.py
from django.forms import ModelForm
from .models import Room, User

class RoomForm(ModelForm):
    class Meta:
        model = Room
        fields = ['name','topic','description']

class UserForm(ModelForm):
    class Meta:
        model = User
        fields = ['name','username','email','bio']

home/api/views.py
from rest_framework.decorators import api_view
from rest_framework.response import Response
from home.models import Room, Topic
from .serializers import RoomSerializer, TopicSerializer

@api_view(['GET'])
def get_routes(request):
    routes = [
        'GET /api',
        'GET /api/rooms',
        'GET /api/rooms/:id',
        'GET /api/topics'
    ]
    res = {'routes':routes}
    return Response(res)

@api_view(['GET'])
def get_rooms(request):
    rooms = Room.objects.all()
    serializer = RoomSerializer(rooms, many=True)
    res = {'rooms':serializer.data}
    return Response(res)

@api_view(['GET'])
def get_room(request,pk):
    room = Room.objects.get(id=pk)
    serializer = RoomSerializer(room, many=False)
    res = {'room':serializer.data}
    return Response(res)

@api_view(['GET'])
def get_topics(request):
    data = Topic.objects.all()
    topics = TopicSerializer(data, many=True)
    res = {'topics':topics.data}
    return Response(res)

home/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login,logout
from .models import Topic, Room, Message, User
from django.core.mail import EmailMessage
from .forms import RoomForm, UserForm
from django.db.models import Q
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from django.shortcuts import get_object_or_404
from django.http import Http404
# Room 
def index(request):

    q = request.GET.get('q') if request.GET.get('q') != None else ''

    topics = Topic.objects.all()[:5]
    rooms = Room.objects.filter(
        Q(topic__name__icontains=q) |
        Q(name__icontains=q) |
        Q(description__icontains=q))

    room_messages = Message.objects.filter(
        Q(room__topic__name__icontains=q) |
        Q(room__name__icontains=q)
        ).order_by('-created_at')[:3]
    context = {'topics':topics, 'rooms':rooms, 'room_messages': room_messages}
    return render(request, 'home/index.html', context)

def room(request,pk):
    try:
        get_room = Room.objects.get(id=pk)
    except:
        messages.error(request,'We\'re not able to fetch the room or it does not exist anymore.')
        return redirect('index')
    room_messages = get_room.message_set.all().order_by('-created_at')
    participants = get_room.participants.all()

    if request.method == 'POST':
        message_body = request.POST.get('message_body')
        message = Message.objects.create(
            host = request.user,
            room = get_room,
            body = message_body
        )
        get_room.participants.add(request.user)
        return redirect('room',pk=get_room.id)

    context={'room':get_room, 'room_messages':room_messages, 'participants':participants}
    return render(request, 'home/room.html',context)

def topics(request):
    q = request.GET.get('q') if request.GET.get('q') != None else ''

    topics=Topic.objects.filter(name__icontains=q)

    context={'topics':topics}
    return render(request, 'home/topics.html',context)

def activity(request):
    room_messages = Message.objects.all().order_by('-created_at')[:3]
    context = {'room_messages':room_messages}
    return render(request, 'home/activity.html', context)

## Room CRUD

@login_required
def update_room(request,pk):
    try:
        room = Room.objects.get(id=pk)
    except:
        messages.error(request,'We\'re not able to fetch the room or it does not exist anymore.')
        return redirect('index')

    if room.host != request.user:
        messages.error(request, 'You\'re not authorized to edit this room details. Please contact the room host.')
        return redirect('room', pk=room.id)
    if request.method == 'POST':
        room_name = request.POST.get('room_name')
        room_topic = request.POST.get('room_topic')
        room_about = request.POST.get('room_about')
        topic,created = Topic.objects.get_or_create(name=room_topic)
        room.name = room_name
        room.topic = topic
        room.description = room_about
        room.save()
        return redirect('index')
    context = {'action':'Update','room':room}
    return render(request, 'home/room_form.html', context)

@login_required
def create_room(request):
    # form = RoomForm()
    if request.method == 'POST':
        # form = RoomForm(request.POST)
        # if form.is_valid():
        #     form.save(commit=False)
        #     form.host = request.user
        #     form.save()
        #     return redirect('index')
        room_name = request.POST.get('room_name')
        room_topic = request.POST.get('room_topic')
        room_about = request.POST.get('room_about')
        topic,created = Topic.objects.get_or_create(name=room_topic)
        room = Room.objects.create(
            name=room_name, 
            host=request.user, 
            topic=topic, 
            description=room_about)
        room.participants.add(request.user)
        return redirect('room',pk=room.id)

    topics = Topic.objects.all()
    context = {'topics':topics, 'action':'Create'}
    return render(request, 'home/room_form.html', context)

@login_required
def delete_room(request,pk):
    try:
        room = Room.objects.get(id=pk)
    except:
        messages.error(request,'We\'re not able to fetch the room or it does not exist anymore.')
        return redirect('index')

    if request.method == 'POST':
        if room.host != request.user:
            messages.error(request, 'You\'re not authorized to perform any action in this room. Please contact the room host.')
            return redirect('room', pk=room.id)
        room = Room.objects.get(id=pk)
        room.delete()
        return redirect('index')

    context = {'room':room}
    return render(request, 'home/delete.html',context)

@login_required
def delete_message(request,pk):
    message = Message.objects.get(id=pk)
    room = message.room
    if request.method == 'POST':
        message.delete()
        return redirect('room',pk=room.id)
    context = {'message':message, 'room':room}
    return render(request, 'home/delete.html', context)

## Authentication
def register_user(request):
    form = UserCreationForm()
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.username = user.username.lower()
            user.save()
            return redirect('login_user')
    context = {'form':form}
    return render(request, 'home/signup.html', context)

def login_user(request):
    if request.user.is_authenticated:
        return redirect('index')
    if request.method == 'POST':
        email = request.POST.get('email')
        password = request.POST.get('password')
        user = authenticate(request, username=email, password=password)
        if user is not None:
            login(request,user)
            return redirect('index')
        else: 
            messages.error(request, 'Incorrect username or password')

    return render(request, 'home/login.html')

def logout_user(request):
    logout(request)
    return redirect('index')

## User Section
@login_required
def profile_settings(request):
    user = request.user
    form = UserForm(instance=user)

    if request.method == 'POST':
        print('I\'m feeling really good. I mean why not')
        form = UserForm(request.POST, instance=user)
        if form.is_valid():
            form.save()
            messages.info(request,'Profile updated successfully')
            return redirect('profile',pk=request.user)
    context = {'form':form}
    return render(request, 'home/settings.html', context)

def user_profile(request,pk:str):
    profile = get_object_or_404(User,username=pk)
    topics = Topic.objects.all()[:5]

    rooms = Room.objects.filter(host=profile)
    room_messages = profile.message_set.all()
    context = {'profile': profile, 'rooms':rooms, 'room_messages':room_messages, 'topics':topics}
    return render(request, 'home/profile.html', context)

home/templates/home/activity.html
{% extends 'base.html' %}
{% block content %}
<div class="layout__box">
  <div class="layout__boxHeader">
    <div class="layout__boxTitle">
      <a href="{% url 'index' %}">
        <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
          <title>arrow-left</title>
          <path
            d="M13.723 2.286l-13.723 13.714 13.719 13.714 1.616-1.611-10.96-10.96h27.625v-2.286h-27.625l10.965-10.965-1.616-1.607z">
          </path>
        </svg>
      </a>
      <h3>Recent Activities</h3>
    </div>
  </div>

  <div class="activities-page layout__body">
    {% for message in room_messages %}

    <div class="activities__box">
      <div class="activities__boxHeader roomListRoom__header">
        <a href="{% url 'profile' message.host %}" class="roomListRoom__author">
          <div class="avatar avatar--small">
            <img src="{{message.host.avatar.url}}" />
          </div>
          <p>
            @{{message.host}}
            <span>{{message.created_at | timesince}} ago</span>
          </p>
        </a>
        <div class="roomListRoom__actions">
          <a href="{% url 'room' message.room.id %}">
            <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
              <title>remove</title>
              <path
                d="M27.314 6.019l-1.333-1.333-9.98 9.981-9.981-9.981-1.333 1.333 9.981 9.981-9.981 9.98 1.333 1.333 9.981-9.98 9.98 9.98 1.333-1.333-9.98-9.98 9.98-9.981z">
              </path>
            </svg>
          </a>
        </div>
      </div>
      <div class="activities__boxContent">
        <p>replied to post in <a href="{% url 'room' message.room.id %}">{{message.room}}</a></p>
        <div class="activities__boxRoomContent">
          {{message }} ...
        </div>
      </div>
    </div>
    {% endfor %}
    
  </div>
</div>
{% endblock content %}

home/templates/home/activity_component.html
    <!-- Activities Start -->
    <div class="activities">
        <div class="activities__header">
          <h2>Recent Activities</h2>
        </div>
        {% if not room_messages %}
        <p> No recent activities available. </p>
        {% else %}
        {% for message in room_messages %}
        <div class="activities__box">
          
          <div class="activities__boxHeader roomListRoom__header">
            <a href="{% url 'profile' message.host %}" class="roomListRoom__author">
              <div class="avatar avatar--small">
                <img src="{{message.host.avatar.url}}" />
              </div>
              <p>
                @{{message.host}}
                <span>{{message.created_at | timesince}} ago</span>
              </p>
            </a>
          </div>
          <div class="activities__boxContent">
            <p>replied to post in <a href="{% url 'room' message.room.id %}">{{message.room}}</a></p>
            <a href="{% url 'room' message.room.id %}">
              <div class="activities__boxRoomContent">
                {{message }} ...
              </div>
            </a>
          </div>
        </div>
        {% endfor %}
        {% endif %}
      </div>
      <!-- Activities End -->

home/templates/home/create-room.html
{% extends 'home/base.html' %}
{% block content %}
  <main class="create-room layout">
    <div class="container">
      <div class="layout__box">
        <div class="layout__boxHeader">
          <div class="layout__boxTitle">
            <a href="{% url 'index' %}">
              <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                <title>arrow-left</title>
                <path
                  d="M13.723 2.286l-13.723 13.714 13.719 13.714 1.616-1.611-10.96-10.96h27.625v-2.286h-27.625l10.965-10.965-1.616-1.607z">
                </path>
              </svg>
            </a>
            <h3>Create Study Room</h3>
          </div>
        </div>
        <div class="layout__body">
          <form class="form" method="POST">
            {% csrf_token %}
            <!-- <div class="form__group">
              <label for="room_name">Room Name</label>
              <input id="room_name" name="room_name" type="text" placeholder="E.g. Mastering Python + Django" />
            </div>

            <div class="form__group">
              <label for="room_topic">Topic</label>
              <input required type="text" name="topic" id="room_topic" list="topic-list" />
              <datalist id="topic-list">
                <select id="room_topic" name="room_topic">
                  <option value="#" disabled>Select your topic</option>
                  {% for topic in topics %}
                  <option value="{{topic}}">{{topic}}</option>
                  {% endfor %}
                </select>
              </datalist>
   
            </div>


            <div class="form__group">
              <label for="room_about">About</label>
              <textarea name="room_about" id="room_about" placeholder="Write about your study group..."></textarea>
            </div> -->

            <div class="form__group">
              {{ form }}
            </div>
         

            <div class="form__action">
              <a class="btn btn--dark" href="{% url 'index' %}">Cancel</a>
              <button class="btn btn--main" type="submit">Create Room</button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </main>
{% endblock content %}

home/templates/home/delete.html
{% extends 'base.html' %}
{% block content %}
    <main class="delete-item layout">
        <div class="container">
            <div class="layout__box">
                <div class="layout__boxHeader">
                    <div class="layout__boxTitle">
                        <a href="{% url 'room' room.id %}">
                            <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32"
                                viewBox="0 0 32 32">
                                <title>arrow-left</title>
                                <path
                                    d="M13.723 2.286l-13.723 13.714 13.719 13.714 1.616-1.611-10.96-10.96h27.625v-2.286h-27.625l10.965-10.965-1.616-1.607z">
                                </path>
                            </svg>
                        </a>
                        <h3>Back</h3>
                    </div>
                </div>
                <div class="layout__body">
                    <form class="form" method="POST">
            
                        {% csrf_token %}
                       
                        <div class="form__group">
                            {% if message %}
                            <p>Are you sure you want to delete Message "{{ message }}" in Room <a href="{% url 'room' room.id %}"> {{ room.name }} </a> ?</p>
                            {% else %}
                            <p>Are you sure you want to delete Room <a href="{% url 'room' room.id %}"> {{ room.name }} </a>?</p>
                            {% endif %}
                        </div>
                        
                        

                        <div class="for__group">

                            <input class="btn btn--main" type="submit" value="Confirm" />
                        </div>

                    </form>
                </div>
            </div>
        </div>
    </main>
{% endblock content %}

home/templates/home/index.html
{% extends 'base.html' %}
{% block content %}
<main class="layout layout--3">
  <div class="container">
  
    {% include 'home/topic_component.html' %}

        <!-- Room List Start -->
        <div class="roomList">
          <div class="mobile-menu">
            <form class="header__search">
              <label>
                <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                  <title>search</title>
                  <path
                    d="M32 30.586l-10.845-10.845c1.771-2.092 2.845-4.791 2.845-7.741 0-6.617-5.383-12-12-12s-12 5.383-12 12c0 6.617 5.383 12 12 12 2.949 0 5.649-1.074 7.741-2.845l10.845 10.845 1.414-1.414zM12 22c-5.514 0-10-4.486-10-10s4.486-10 10-10c5.514 0 10 4.486 10 10s-4.486 10-10 10z">
                  </path>
                </svg>
                <input placeholder="Search for posts" name="q"/>
              </label>
            </form>
            <div class="mobile-menuItems">
              <a class="btn btn--main btn--pill" href="{% url 'index' %}">Browse Topics</a>
              <a class="btn btn--main btn--pill" href="#">Recent Activities</a>
            </div>
          </div>
          <div class="roomList__header">
            <div>
              <h2>Study Room</h2>
              {% if rooms %}
              <p>{{ rooms.count }} Rooms available</p>
              {% else %}
              <p> No Rooms available</p>
    
              {% endif %}
            </div>
            <a class="btn btn--main" href="{% url 'create_room' %}">
              <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                <title>add</title>
                <path
                  d="M16.943 0.943h-1.885v14.115h-14.115v1.885h14.115v14.115h1.885v-14.115h14.115v-1.885h-14.115v-14.115z">
                </path>
              </svg>
              Create Room
            </a>
          </div>

          {% include 'home/room_component.html' %}
        </div>
        <!-- Room List End -->

    {% include 'home/activity_component.html' %}

  </div>
</main>
{% endblock content %}

home/templates/home/login.html
{% extends 'base.html' %}
{% block content %}
        <div class="layout__box">
          <div class="layout__boxHeader">
            <div class="layout__boxTitle">
              <h3>Login</h3>
            </div>
          </div>
          <div class="layout__body">
            <h2 class="auth__tagline">Find your study partner</h2>

            <form class="form" method="POST">
              {% csrf_token %}
              <div class="form__group form__group">
                <label for="email">Email</label>
                <input id="email" name="email" type="email" placeholder="jon_doe@mail.co" />
              </div>
              <div class="form__group">
                <label for="password">Password</label>
                <input
                  id="password"
                  name="password"
                  type="password"
                  placeholder="&bull;&bull;&bull;&bull;&bull;&bull;&bull;&bull;"
                />
              </div>

              <button class="btn btn--main" type="submit">
                <svg
                  version="1.1"
                  xmlns="http://www.w3.org/2000/svg"
                  width="32"
                  height="32"
                  viewBox="0 0 32 32"
                >
                  <title>lock</title>
                  <path
                    d="M27 12h-1v-2c0-5.514-4.486-10-10-10s-10 4.486-10 10v2h-1c-0.553 0-1 0.447-1 1v18c0 0.553 0.447 1 1 1h22c0.553 0 1-0.447 1-1v-18c0-0.553-0.447-1-1-1zM8 10c0-4.411 3.589-8 8-8s8 3.589 8 8v2h-16v-2zM26 30h-20v-16h20v16z"
                  ></path>
                  <path
                    d="M15 21.694v4.306h2v-4.306c0.587-0.348 1-0.961 1-1.694 0-1.105-0.895-2-2-2s-2 0.895-2 2c0 0.732 0.413 1.345 1 1.694z"
                  ></path>
                </svg>

                Login
              </button>
            </form>

            <div class="auth__action">
              <p>Haven't signed up yet?</p>
              <a href="{% url 'register_user' %}" class="btn btn--link">Sign Up</a>
            </div>
          </div>
        </div>
{% endblock content %}

home/templates/home/profile.html
{% extends 'base.html' %}
{% block content %}
  <main class="profile-page layout layout--3">
    <div class="container">
      
      {% include 'home/topic_component.html' %}


      <!-- Room List Start -->
      <div class="roomList">
        <div class="profile">
          <div class="profile__avatar">
            <div class="avatar avatar--large active">
              <img src="{{profile.avatar.url}}" />
            </div>
          </div>
          <div class="profile__info">
            <h3>
              {% if profile.name %}
                {{profile.name}}
              {% else %}
                {{profile.username}}
              {% endif %}
            </h3>
            <p>@{{profile.username}}</p>
            <a href="{% url 'profile_settings' %}" class="btn btn--main btn--pill">Edit Profile</a>
          </div>
          <div class="profile__about">
            <h3>About</h3>
            <p>
              {{profile.bio}}
            </p>
          </div>
        </div>

        <div class="roomList__header">
          <div>
            {% if rooms %}
            <h2>Study Rooms Hosted by {{profile}}</a>
              {% else %}
            <h2>There are not Study Rooms Hosted by {{profile.username}} </a>
              {% endif %}
            </h2>
          </div>
        </div>
        {% include 'home/room_component.html' %}

      </div>
      <!-- Room List End -->

    <!-- Activities Start -->
    <div class="activities">
      <div class="activities__header">
        <h2>Recent Activities</h2>
      </div>
      {% if not room_messages %}
      <p> No recent activities available. </p>
      {% else %}
      {% for message in room_messages %}
      <div class="activities__box">
        
        <div class="activities__boxHeader roomListRoom__header">
          <a href="{% url 'profile' message.host %}" class="roomListRoom__author">
            <div class="avatar avatar--small">
              <img src="https://randomuser.me/api/portraits/women/11.jpg" />
            </div>
            <p>
              @{{message.host}}
              <span>{{message.created_at | timesince}} ago</span>
            </p>
          </a>
          <div class="roomListRoom__actions">
            <a href="#">
              <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                <title>remove</title>
                <path
                  d="M27.314 6.019l-1.333-1.333-9.98 9.981-9.981-9.981-1.333 1.333 9.981 9.981-9.981 9.98 1.333 1.333 9.981-9.98 9.98 9.98 1.333-1.333-9.98-9.98 9.98-9.981z">
                </path>
              </svg>
            </a>
          </div>
        </div>
        <div class="activities__boxContent">
          <p>replied to post in <a href="{% url 'room' message.room.id %}">{{message.room}}</a></p>
          <a href="{% url 'room' message.room.id %}">
            <div class="activities__boxRoomContent">
              {{message }} ...
            </div>
          </a>
        </div>
      </div>
      {% endfor %}
      {% endif %}
    </div>
    <!-- Activities End -->
    </div>
  </main>
{% endblock content %}

home/templates/home/room_component.html
{% if rooms %}

{% for room in rooms %}
<div class="roomListRoom">
    <div class="roomListRoom__header">
        <a href="{% url 'profile' room.host %}" class="roomListRoom__author">
            <div class="avatar avatar--small">
                <img src="{{room.host.avatar.url}}" />
            </div>
            <span>{{ room.host }}</span>
        </a>
        <div class="roomListRoom__actions">
            <span> {{ room.updated_at | timesince }} ago</span>
        </div>
    </div>
    <div class="roomListRoom__content">
        <a href="{% url 'room' room.id %}">{{ room.name }}</a>
        <p>
            {{ room.description }}
        </p>
    </div>
    <div class="roomListRoom__meta">
        <a href="{% url 'room' room.id %}" class="roomListRoom__joined">
            <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                <title>user-group</title>
                <path
                    d="M30.539 20.766c-2.69-1.547-5.75-2.427-8.92-2.662 0.649 0.291 1.303 0.575 1.918 0.928 0.715 0.412 1.288 1.005 1.71 1.694 1.507 0.419 2.956 1.003 4.298 1.774 0.281 0.162 0.456 0.487 0.456 0.85v4.65h-4v2h5c0.553 0 1-0.447 1-1v-5.65c0-1.077-0.56-2.067-1.461-2.584z">
                </path>
                <path
                    d="M22.539 20.766c-6.295-3.619-14.783-3.619-21.078 0-0.901 0.519-1.461 1.508-1.461 2.584v5.65c0 0.553 0.447 1 1 1h22c0.553 0 1-0.447 1-1v-5.651c0-1.075-0.56-2.064-1.461-2.583zM22 28h-20v-4.65c0-0.362 0.175-0.688 0.457-0.85 5.691-3.271 13.394-3.271 19.086 0 0.282 0.162 0.457 0.487 0.457 0.849v4.651z">
                </path>
                <path
                    d="M19.502 4.047c0.166-0.017 0.33-0.047 0.498-0.047 2.757 0 5 2.243 5 5s-2.243 5-5 5c-0.168 0-0.332-0.030-0.498-0.047-0.424 0.641-0.944 1.204-1.513 1.716 0.651 0.201 1.323 0.331 2.011 0.331 3.859 0 7-3.141 7-7s-3.141-7-7-7c-0.688 0-1.36 0.131-2.011 0.331 0.57 0.512 1.089 1.075 1.513 1.716z">
                </path>
                <path
                    d="M12 16c3.859 0 7-3.141 7-7s-3.141-7-7-7c-3.859 0-7 3.141-7 7s3.141 7 7 7zM12 4c2.757 0 5 2.243 5 5s-2.243 5-5 5-5-2.243-5-5c0-2.757 2.243-5 5-5z">
                </path>
            </svg>
            {{ room.participants.count }} people Joined
        </a>
        <p class="roomListRoom__topic">{{ room.topic }}</p>
    </div>
</div>
{% endfor %}
{% endif %}

home/templates/home/topic_component.html
    <!-- Topics Start -->
    <div class="topics">
        <div class="topics__header">
          <h2>Browse Topics</h2>
        </div>
  
        {% if topics %}
        <ul class="topics__list">
          <li>
            <a href="{% url 'index' %}" class="active">All <span>{{topics.count}}</span></a>
          </li>
          {% for topic in topics %}
          <li>
            <a href="?q={{topic.name}}">{{topic.name}} <span>{{topic.room_set.all.count}}</span></a>
          </li>
          {% endfor %}
        </ul>
        <a class="btn btn--link" href="{% url 'topics' %}">
            More
            <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
              <title>chevron-down</title>
              <path d="M16 21l-13-13h-3l16 16 16-16h-3l-13 13z"></path>
            </svg>
          </a>
        {% else %}
            <a href="{% url 'index' %}" class="active">No Topics available..</span></a>
        {% endif %}
        
      </div>
      <!-- Topics End -->